### ISSUE TITLE
How to start up client program?

### ISSUE THREAD

**Issue by mylover106** [UbiquitousLearning/End2end-Federated-Learning#1]
Hello, very appreciate for your contribution!
Can you further explain how to start the client program?
Do I need some extra tools to pack the client program?
I am not famaliar with java and stucked with running client program.
Thanks for your help!

**Comment by destinyson** [comment]
Hello, thank you for your support and sorry for answering too late.
To start the client program, you need Android Studio, and install the app to devices.
You can get Android Studio by this site: https://developer.android.com/

**Comment by mylover106** [comment]
Thanks for your time! It is clear now!
